-- Performance / cost: seven indexes covering predicates that services filter
-- on today with nothing to back them, each of which currently forces a
-- sequential scan of the whole table.
--
-- Purely additive (CREATE INDEX only) -- no column, constraint or data is
-- touched, so this is safe to apply with `prisma migrate deploy` while an
-- older instance is still serving traffic.
--
-- HAND-AUTHORED, NOT generated by `prisma migrate diff`: there is no
-- DATABASE_URL available in the environment this was written in, so no
-- database was contacted and nothing here has been executed. It matches the
-- @@index blocks added to prisma/schema.prisma in the same commit and
-- follows the naming Prisma itself emits (<Model>_<cols>_idx), but it should
-- be confirmed with `prisma migrate diff --from-migrations prisma/migrations
-- --to-schema-datamodel prisma/schema.prisma --script` (expected output:
-- empty) before it is deployed.

-- User: both Stripe ids are resolved with `findFirst` on every webhook
-- (stripe.service.ts handleSubscriptionUpdated / handleSubscriptionDeleted /
-- handleInvoicePaymentFailed / handleInvoicePaid). Neither was indexed, so
-- each webhook scanned the entire User table -- a cost that grows with total
-- signups, on a path Stripe retries when it is slow.
-- CreateIndex
CREATE INDEX "User_stripeCustomerId_idx" ON "User"("stripeCustomerId");

-- CreateIndex
CREATE INDEX "User_stripeSubscriptionId_idx" ON "User"("stripeSubscriptionId");

-- TimeEntry.taskId: filtered on its own, WITHOUT userId, by the task
-- completion path in tasks.service.ts ("how much of this task was already
-- tracked?"). Neither [userId] nor [userId, date] can serve that, so every
-- task completion scanned the largest and fastest-growing table in the
-- schema. Postgres does not index foreign keys automatically, so this also
-- covers the `ON DELETE SET NULL` fixup that runs on every Task delete.
-- CreateIndex
CREATE INDEX "TimeEntry_taskId_idx" ON "TimeEntry"("taskId");

-- TimeEntry.scheduleBlockId: same unindexed-FK situation. Every schedule
-- block delete had to scan TimeEntry, and schedule.service.ts's deleteAll
-- does that as a single bulk deleteMany.
-- CreateIndex
CREATE INDEX "TimeEntry_scheduleBlockId_idx" ON "TimeEntry"("scheduleBlockId");

-- ScheduleBlock: userId and dayOfWeek are filtered together by getByDay and
-- by checkTimeConflict, and checkTimeConflict runs once per block inside the
-- recurring-series update loop. The existing single-column indexes let
-- Postgres use only one of them, and [dayOfWeek] is near-useless at seven
-- distinct values. Same shape of fix as TimeEntry(userId, date).
-- CreateIndex
CREATE INDEX "ScheduleBlock_userId_dayOfWeek_idx" ON "ScheduleBlock"("userId", "dayOfWeek");

-- ScheduleBlock.goalId: unindexed FK with ON DELETE SET NULL, so every Goal
-- delete scanned ScheduleBlock. Task.goalId and TimeEntry.goalId are both
-- already indexed; this one was missed.
-- CreateIndex
CREATE INDEX "ScheduleBlock_goalId_idx" ON "ScheduleBlock"("goalId");

-- GoalReflection.goalId: the unique constraint leads with userId, so it
-- cannot serve the goalId-only lookup that ON DELETE CASCADE issues on every
-- Goal delete.
-- CreateIndex
CREATE INDEX "GoalReflection_goalId_idx" ON "GoalReflection"("goalId");
